<div class="jumbotron" style="background:#aaccff;margin-bottom:0px">
  <h1>Yap!</h1>
  <p>A yelp like review site for local businesses</p>
</div>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">YapServer</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="login"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="logout"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
