<div class="container">
  $header$
  
  <div class="panel panel-primary">
    <div class="panel-heading">
      Welcome! $username$
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <div class="well">
            <h3><a href="business">View Business</a></h3>
            <p>To see the list of available business...</p>
	      </div>
	    </div>
	    <div class="col-md-6">
	      <div class="well">
	        <h3><a href="logout">Logout</a></h3>
	        <p>To log out of your account...</p>
	      </div>
	    </div>
	  </div>
    </div>
  </div>
</div>