<div class="container">
  $header$
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <h3><a href="login">Login</a></h3>
        <p>Click here to login with your account...</p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h3><a href="signup">SignUp</a></h3>
        <p>Click here to signup for a new account...</p>
      </div>
    </div>
  </div>
</div>